### PR TITLE
Add "crashdump" dataset for storing core files

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/98/) (`internal-dev` only is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/99/)).

**Comment by pzakha** [comment]
It looks like appliance-build is failing, perhaps because it tries to mount `rpool/crashdump` onto `/mnt/var/crash`.

**Comment by basil** [comment]
bors delegate+

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/129/) (`internal-dev` only is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/130/)).

**Pull request merged**
