### PR TITLE
Expose root filesystem device to upgrade container

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
cc: @pzakha @grwilson

```
$ sudo /var/dlpx-update/latest/upgrade-container create in-place
delphix.tQXzvkJ
$ cat /etc/systemd/nspawn/delphix.tQXzvkJ.nspawn 
[Exec]
PrivateUsers=no
[Network]
Private=yes
[Files]
PrivateUsersChown=no
Bind=/dev/zfs
BindReadOnly=/dev/xvda1
Bind=/var/dlpx-update
Bind=/var/delphix/dropbox
$ sudo /var/dlpx-update/latest/upgrade-container start delphix.tQXzvkJ
$ sudo systemd-run --machine delphix.tQXzvkJ --pty /bin/bash
Running as unit: run-u29.service
Press ^] three times within 1s to disconnect TTY.
# dd if=/dev/urandom of=/dev/xvda1
dd: failed to open '/dev/xvda1': Operation not permitted
# sudo apt-get purge kdump-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  delphix-entire* delphix-masking* delphix-platform* delphix-virtualization* kdump-tools*
0 upgraded, 0 newly installed, 5 to remove and 0 not upgraded.
After this operation, 2,457 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 141504 files and directories currently installed.)
Removing delphix-entire (2019.1.7.8) ...
Removing delphix-masking (1.0.0-20190106T160846) ...
Removing delphix-virtualization (2019.1.7.8) ...
+ case $1 in
+ pam-auth-update --remove delphix-pam
+ rm /lib/x86_64-linux-gnu/security/pam_delphix_account.so /lib/x86_64-linux-gnu/security/pam_delphix_auth.so /lib/x86_64-linux-gnu/security/pam_delphix_session.so
+ sed -E -i 's/^(passwd:.*)\sdelphix($|\s.*)$/\1 \2/' /etc/nsswitch.conf
+ sed -E -i 's/(\s*enable-cache\s+passwd\s+)no/\1yes/' /etc/nscd.conf
+ systemctl disable delphix-fluentd.service
Removed /etc/systemd/system/multi-user.target.wants/delphix-fluentd.service.
+ systemctl disable delphix-mgmt.service
Removed /etc/systemd/system/multi-user.target.wants/delphix-mgmt.service.
+ systemctl disable delphix-postgres@.service
Removed /etc/systemd/system/multi-user.target.wants/delphix-postgres@default.service.
+ systemctl disable delphix-stat.service
Removed /etc/systemd/system/multi-user.target.wants/delphix-stat.service.
+ exit 0
Removing delphix-platform (1.0.0-delphix-2019.01.07.07) ...
+ case $1 in
+ systemctl disable delphix-platform.service
Removed /etc/systemd/system/default.target.wants/delphix-platform.service.
+ exit 0
Removing kdump-tools (1:1.6.3-2) ...
Generating grub configuration file ...
grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
Found linux image: /boot/vmlinuz-4.15.0-43-generic
Found initrd image: /boot/initrd.img-4.15.0-43-generic
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
/usr/sbin/grub-probe: warning: disk does not exist, so falling back to partition device /dev/xvda1.
done
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
(Reading database ... 127470 files and directories currently installed.)
Purging configuration files for kdump-tools (1:1.6.3-2) ...
Purging configuration files for delphix-platform (1.0.0-delphix-2019.01.07.07) ...
dpkg: warning: while removing delphix-platform, directory '/etc/delphix-platform' not empty so not removed
Processing triggers for systemd (237-3ubuntu10.9) ...
```

**Comment by prakashsurya** [comment]
FWIW, it seems like using `BindReadOnly=/dev` also works... from inside the container, I see the devices (and lots of other things in `/dev`):
```
root@ip-10-110-196-54:/# ls -l /dev/xvd*
brw-rw---- 1 root disk 202,  0 Jan  7 18:53 /dev/xvda
brw-rw---- 1 root disk 202,  1 Jan  7 21:25 /dev/xvda1
brw-rw---- 1 root disk 202,  2 Jan  7 18:53 /dev/xvda2
brw-rw---- 1 root disk 202, 16 Jan  7 18:53 /dev/xvdb
brw-rw---- 1 root disk 202, 32 Jan  7 18:53 /dev/xvdc
brw-rw---- 1 root disk 202, 48 Jan  7 18:53 /dev/xvdd

# for d in /dev/xvd*; do dd if=/dev/zero of=$d; done
dd: failed to open '/dev/xvda': Operation not permitted
dd: failed to open '/dev/xvda1': Operation not permitted
dd: failed to open '/dev/xvda2': Operation not permitted
dd: failed to open '/dev/xvdb': Operation not permitted
dd: failed to open '/dev/xvdc': Operation not permitted
dd: failed to open '/dev/xvdd': Operation not permitted
```
I'm unsure if this approach would come with other drawbacks, though.

**Comment by pzakha** [comment]
@prakashsurya Thanks for the reply. So the following 2 lines are what I was looking for:
```
[pid 29034] 22:22:22.366249 mount("/dev/xvda1", "/var/lib/machines/delphix.jCXXtZo/dev/xvda1", NULL, MS_BIND|MS_REC, NULL) = 0
[pid 29034] 22:22:22.367997 mount(NULL, "/var/lib/machines/delphix.jCXXtZo/dev/xvda1", NULL, MS_RDONLY|MS_NOSUID|MS_REMOUNT|MS_BIND, NULL) = 0
```
This seems to be in agreement with what I've read online and this exert of `man mount`:
>>>
       mount(8) since v2.27 allows to change the mount options by passing the relevant options along with --bind.  For example:

              mount -o bind,ro foo foo

       This feature is not supported by the Linux kernel; it is implemented in userspace by an additional mount(2) remounting system call.  This solution is not atomic.

       The alternative (classic) way to create a read-only bind mount is to use the remount operation, for example:

              mount --bind olddir newdir
              mount -o remount,bind,ro olddir newdir

       Note that a read-only bind will create a read-only mountpoint (VFS entry), but the original filesystem superblock will still be writable, meaning that the olddir will be writable, but the newdir  will  be
       read-

**Pull request merged**
