### PR TITLE
Use Ubuntu mirrors provided by EC2 via live-build

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/202/)

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/203/)

**Comment by prakashsurya** [comment]
@pzakha @shartse should we move forward with this?

**Comment by pzakha** [comment]
Sure, it shouldn't hurt.

**Pull request merged**
