### PR TITLE
DLPX-80287 remove unnecessary "recommended" packages from appliance

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push -v external-standard --no-tests` is [here](http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/1235/)

**Comment by prakashsurya** [comment]
This change appears to remove 176 packages from the appliance; e.g.
```
$ wc -l before/external-standard-esx.packages.list 
866 before/external-standard-esx.packages.list

$ wc -l after/external-standard-esx.packages.list 
690 after/external-standard-esx.packages.list
```

But this appears to be a minimal size difference in the actual VM image; only about 165MB:
```
$ aws s3 ls s3://dev-de-images/builds/jenkins-selfservice/appliance-build/master/pre-push/997/external-standard-esx/
2022-03-22 22:56:16        198 MD5SUMS
2022-03-22 22:56:16        294 SHA256SUMS
2022-03-22 22:56:16 4539124461 external-standard-esx.debs.tar.gz
2022-03-22 22:56:16 7537018880 external-standard-esx.ova
2022-03-22 22:56:16      20440 external-standard-esx.packages.list

$ aws s3 ls s3://snapshot-de-images/builds/jenkins-ops/appliance-build/master/nightly/108/external-standard-esx/
2022-03-22 07:00:53        198 MD5SUMS
2022-03-22 07:00:53        294 SHA256SUMS
2022-03-22 07:00:53 4621858962 external-standard-esx.debs.tar.gz
2022-03-22 07:00:53 7710044160 external-standard-esx.ova
2022-03-22 07:00:53      25569 external-standard-esx.packages.list
```

The full list of packages removed is below:
```
$ diff -u0 before/external-standard-esx.packages.list after/external-standard-esx.packages.list
--- before/external-standard-esx.packages.list  2022-03-22 07:00:53.000000000 +0000
+++ after/external-standard-esx.packages.list   2022-03-22 22:56:16.000000000 +0000
@@ -5,2 +4,0 @@
-alsa-topology-conf=1.2.2-1
-alsa-ucm-conf=1.2.2-1ubuntu0.12
@@ -9 +6,0 @@
-apparmor=2.13.3-7ubuntu5.1
@@ -30 +26,0 @@
-blt=2.5.3+dfsg-4
@@ -33 +28,0 @@
-bridge-utils=1.6-2ubuntu1
@@ -51 +45,0 @@
-crash=7.2.8-1ubuntu1.20.04.1
@@ -57 +50,0 @@
-dbus-user-session=1.12.16-2ubuntu2.1
@@ -59,2 +51,0 @@
-dconf-gsettings-backend=0.36.0-1
-dconf-service=0.36.0-1
@@ -66 +57 @@
-delphix-build-info=1.0.0-delphix-2022.03.22.06.19.08-9710126a
+delphix-build-info=1.0.0-delphix-2022.03.22.22.11.32-691f0b89
@@ -68 +59 @@
-delphix-masking=1.0.0-20220322T034447
+delphix-masking=1.0.0-20220322T155654
@@ -72,2 +63,2 @@
-delphix-virtualization=2022.03.22.02
-delphix-zfs=2.1.99-delphix+2022.03.21.19
+delphix-virtualization=2022.03.22.21
+delphix-zfs=2.1.99-delphix+2022.03.22.19
@@ -75 +65,0 @@
-dirmngr=2.2.19-3ubuntu2.1
@@ -80,3 +69,0 @@
-dmsetup=2:1.02.167-1ubuntu1
-dns-root-data=2019052802
-dnsmasq-base=2.80-1.1ubuntu1.4
@@ -92 +78,0 @@
-eatmydata=105-7
@@ -97 +82,0 @@
-emacs-el=1:26.3+1-1ubuntu2
@@ -103 +87,0 @@
-finalrd=6~ubuntu20.04.1
@@ -110,5 +93,0 @@
-fonts-droid-fallback=1:6.0.1r16-1.1
-fonts-lyx=2.3.4.2-2
-fonts-noto-mono=20200323-1build1~ubuntu20.04.1
-fonts-urw-base35=20170801.1-3
-fuse=2.9.9-3
@@ -118 +96,0 @@
-gdbserver=9.2-0ubuntu1~20.04.1
@@ -121 +98,0 @@
-ghostscript=9.50~dfsg-5ubuntu4.5
@@ -123,15 +99,0 @@
-gir1.2-packagekitglib-1.0=1.1.13-2ubuntu1.1
-git-man=1:2.25.1-1ubuntu3.2
-git=1:2.25.1-1ubuntu3.2
-glib-networking-common=2.64.2-1ubuntu0.1
-glib-networking-services=2.64.2-1ubuntu0.1
-glib-networking=2.64.2-1ubuntu0.1
-gnupg-l10n=2.2.19-3ubuntu2.1
-gnupg-utils=2.2.19-3ubuntu2.1
-gnupg=2.2.19-3ubuntu2.1
-gpg-agent=2.2.19-3ubuntu2.1
-gpg-wks-client=2.2.19-3ubuntu2.1
-gpg-wks-server=2.2.19-3ubuntu2.1
-gpg=2.2.19-3ubuntu2.1
-gpgconf=2.2.19-3ubuntu2.1
-gpgsm=2.2.19-3ubuntu2.1
@@ -147,2 +108,0 @@
-gsettings-desktop-schemas=3.36.0-1ubuntu1
-gsfonts=1:8.11+urwcyr1.0.7~pre44-4.4
@@ -156 +115,0 @@
-ibverbs-providers=28.0-1ubuntu1
@@ -158,3 +116,0 @@
-imagemagick-6-common=8:6.9.10.23+dfsg-2.1ubuntu11.4
-imagemagick-6.q16=8:6.9.10.23+dfsg-2.1ubuntu11.4
-imagemagick=8:6.9.10.23+dfsg-2.1ubuntu11.4
@@ -175,2 +130,0 @@
-isc-dhcp-common=4.4.1-2.1ubuntu5.20.04.2
-iso-codes=4.4-1
@@ -179 +132,0 @@
-javascript-common=11
@@ -189 +141,0 @@
-krb5-locales=1.17-6ubuntu4.1
@@ -197 +148,0 @@
-libappstream4=0.12.10-2
@@ -204 +154,0 @@
-libassuan0=2.5.3-7ubuntu2
@@ -207 +156,0 @@
-libatm1=1:2.5.1-4
@@ -219 +167,0 @@
-libblas3=3.9.0-1build1
@@ -229 +176,0 @@
-libc6-dbg=2.31-0ubuntu9.7
@@ -238,3 +184,0 @@
-libcc1-0=10.3.0-1ubuntu1~20.04
-libcgi-fast-perl=1:2.15-1
-libcgi-pm-perl=4.46-1
@@ -242 +185,0 @@
-libclass-accessor-perl=0.51-1
@@ -244 +186,0 @@
-libcommon-sense-perl=3.74-2build6
@@ -259 +200,0 @@
-libdconf1=0.36.0-1
@@ -262,2 +202,0 @@
-libdjvulibre-text=3.5.27.1-14ubuntu0.1
-libdjvulibre21=3.5.27.1-14ubuntu0.1
@@ -269 +207,0 @@
-libeatmydata1=105-7
@@ -274,3 +211,0 @@
-libencode-locale-perl=1.05-1
-liberror-perl=0.17029-1
-libestr0=0.1.10-2.1
@@ -278,2 +212,0 @@
-libevent-core-2.1-7=2.1.11-stable-1
-libevent-pthreads-2.1-7=2.1.11-stable-1
@@ -282,2 +214,0 @@
-libfastjson4=0.99.8-2
-libfcgi-perl=0.79-1
@@ -286 +216,0 @@
-libfftw3-double3=3.3.8-2ubuntu1
@@ -288 +217,0 @@
-libfile-fcntllock-perl=0.22-3build4
@@ -295,2 +223,0 @@
-libgail-common=2.24.32-4ubuntu4
-libgail18=2.24.32-4ubuntu4
@@ -304 +230,0 @@
-libgdk-pixbuf2.0-bin=2.40.0+dfsg-3ubuntu0.2
@@ -307 +232,0 @@
-libgfortran5=10.3.0-1ubuntu1~20.04
@@ -312,2 +236,0 @@
-libglib2.0-bin=2.64.6-1~ubuntu20.04.4
-libglib2.0-data=2.64.6-1~ubuntu20.04.4
@@ -321,2 +243,0 @@
-libgs9-common=9.50~dfsg-5ubuntu4.5
-libgs9=9.50~dfsg-5ubuntu4.5
@@ -326 +246,0 @@
-libgstreamer1.0-0=1.16.2-2
@@ -328 +247,0 @@
-libgtk2.0-bin=2.24.32-4ubuntu4
@@ -335,4 +253,0 @@
-libhtml-parser-perl=3.72-5
-libhtml-tagset-perl=3.20-4
-libhttp-date-perl=6.05-1
-libhttp-message-perl=6.22-1
@@ -343 +257,0 @@
-libidn11=1.33-2.2ubuntu2
@@ -345,3 +258,0 @@
-libijs-0.35=0.35-15
-libilmbase24=2.3.0-6build1
-libimagequant0=2.12.2-1.1
@@ -349,2 +259,0 @@
-libio-html-perl=1.001-1
-libio-string-perl=1.08-3
@@ -357 +265,0 @@
-libjbig2dec0=0.18-1ubuntu1
@@ -361,2 +268,0 @@
-libjs-jquery-ui=1.12.1+dfsg-5
-libjs-jquery=3.3.1~dfsg-3
@@ -365 +270,0 @@
-libjson-xs-perl=4.020-1build1
@@ -378,2 +282,0 @@
-libksba8=1.3.5-2
-liblapack3=3.9.0-1build1
@@ -386 +288,0 @@
-liblqr-1-0=0.4.2-2.1
@@ -389 +290,0 @@
-liblwp-mediatypes-perl=6.04-1
@@ -395,3 +295,0 @@
-libmagickcore-6.q16-6-extra=8:6.9.10.23+dfsg-2.1ubuntu11.4
-libmagickcore-6.q16-6=8:6.9.10.23+dfsg-2.1ubuntu11.4
-libmagickwand-6.q16-6=8:6.9.10.23+dfsg-2.1ubuntu11.4
@@ -409 +306,0 @@
-libnetpbm10=2:10.0-15.3build1
@@ -425,3 +321,0 @@
-libnpth0=1.6-1
-libnss-mymachines=245.4-4ubuntu3.15
-libnss-systemd=245.4-4ubuntu3.15
@@ -430 +324 @@
-libnvpair1linux=2.1.99-delphix+2022.03.21.19
+libnvpair1linux=2.1.99-delphix+2022.03.22.19
@@ -433,2 +326,0 @@
-libopenexr24=2.3.0-6ubuntu0.5
-libopenjp2-7=2.3.1-1ubuntu4.20.04.1
@@ -437,2 +328,0 @@
-libpackagekit-glib2-18=1.1.13-2ubuntu1.1
-libpam-cap=1:2.32-1
@@ -447,3 +336,0 @@
-libpaper-utils=1.1.28
-libpaper1=1.1.28
-libparse-debianchangelog-perl=1.2.0-13
@@ -464 +350,0 @@
-libproxy1v5=0.4.15-10ubuntu1.2
@@ -474 +359,0 @@
-libquadmath0=10.3.0-1ubuntu1~20.04
@@ -485 +369,0 @@
-libsasl2-modules=2.1.27+dfsg-2ubuntu0.1
@@ -505,2 +388,0 @@
-libsodium23=1.0.18-1
-libsoup2.4-1=2.70.0-1
@@ -515,2 +396,0 @@
-libstemmer0d=0+svn585-2
-libsub-name-perl=0.26-1
@@ -521 +400,0 @@
-libtcl8.6=8.6.10+dfsg-1
@@ -531 +409,0 @@
-libtimedate-perl=2.3200-1
@@ -535,2 +412,0 @@
-libtk8.6=8.6.10-1
-libtypes-serialiser-perl=1.0-1
@@ -541 +416,0 @@
-liburi-perl=1.76-2
@@ -545 +420 @@
-libuutil1linux=2.1.99-delphix+2022.03.21.19
+libuutil1linux=2.1.99-delphix+2022.03.22.19
@@ -551,2 +425,0 @@
-libwebpdemux2=0.6.1-2ubuntu0.20.04.1
-libwebpmux3=0.6.1-2ubuntu0.20.04.1
@@ -557 +429,0 @@
-libwmf0.2-7=0.2.8.4-17ubuntu1
@@ -574 +445,0 @@
-libxft2=2.3.3-0ubuntu1
@@ -581 +451,0 @@
-libxmuu1=2:1.1.3-0ubuntu1
@@ -586 +455,0 @@
-libxss1=1:1.2.3-1
@@ -591,3 +460,3 @@
-libzfs2linux=2.1.99-delphix+2022.03.21.19
-libzfslinux-dev=2.1.99-delphix+2022.03.21.19
-libzpool2linux=2.1.99-delphix+2022.03.21.19
+libzfs2linux=2.1.99-delphix+2022.03.22.19
+libzfslinux-dev=2.1.99-delphix+2022.03.22.19
+libzpool2linux=2.1.99-delphix+2022.03.22.19
@@ -607 +475,0 @@
-logrotate=3.14.0-4ubuntu3
@@ -629 +496,0 @@
-ncurses-term=6.2-0ubuntu2
@@ -634 +500,0 @@
-netpbm=2:10.0-15.3build1
@@ -636 +501,0 @@
-networkd-dispatcher=2.1-2~ubuntu20.04.1
@@ -655,3 +519,0 @@
-os-prober=1.74ubuntu2
-packagekit-tools=1.1.13-2ubuntu1.1
-packagekit=1.1.13-2ubuntu1.1
@@ -671 +532,0 @@
-pinentry-curses=1.1.0-3build1
@@ -673 +533,0 @@
-poppler-data=0.4.9-2
@@ -682 +541,0 @@
-psutils=1.17.dfsg-4
@@ -685 +543,0 @@
-publicsuffix=20200303.0012-1
@@ -690 +547,0 @@
-python-matplotlib-data=3.1.2-1ubuntu4
@@ -701 +557,0 @@
-python3-bcrypt=3.1.7-2ubuntu1
@@ -711 +566,0 @@
-python3-cycler=0.10.0-3
@@ -718 +572,0 @@
-python3-distro=1.4.0-1
@@ -732,2 +585,0 @@
-python3-kerberos=1.1.14-3.1build1
-python3-kiwisolver=1.0.1-3build1
@@ -736 +587,0 @@
-python3-matplotlib=3.1.2-1ubuntu4
@@ -739 +589,0 @@
-python3-nacl=1.3.0-5
@@ -741,2 +590,0 @@
-python3-ntlm-auth=1.1.0-1
-python3-numpy=1:1.17.4-5ubuntu3
@@ -744 +591,0 @@
-python3-olefile=0.46-2
@@ -746,2 +592,0 @@
-python3-paramiko=2.6.0-2
-python3-pil=7.0.0-4ubuntu0.5
@@ -752 +596,0 @@
-python3-pygments=2.3.1+dfsg-1ubuntu2.2
@@ -756,3 +599,0 @@
-python3-requests-kerberos=0.12.0-2
-python3-requests-ntlm=1.1.0-1
-python3-requests-unixsocket=0.2.0-2
@@ -768,2 +608,0 @@
-python3-software-properties=0.99.9.8
-python3-tk=3.8.10-0ubuntu1~20.04
@@ -774,2 +612,0 @@
-python3-winrm=0.3.0-2
-python3-xmltodict=0.12.0-1
@@ -786 +622,0 @@
-rsyslog=8.2001.0-1ubuntu1.1
@@ -801,2 +636,0 @@
-sntp=1:4.2.8p12+dfsg-3ubuntu4.20.04.1
-software-properties-common=0.99.9.8
@@ -804,2 +637,0 @@
-ssh-import-id=5.10-0ubuntu1
-sshpass=1.06-1
@@ -818 +649,0 @@
-tk8.6-blt2.5=2.5.3+dfsg-4
@@ -823 +653,0 @@
-ttf-bitstream-vera=1.10-8
@@ -827 +656,0 @@
-ubuntu-fan=0.12.13
@@ -834,2 +662,0 @@
-unattended-upgrades=2.3ubuntu0.1
-unzip=6.0-25ubuntu1
@@ -850,2 +676,0 @@
-xauth=1:1.1-0ubuntu1
-xdg-user-dirs=0.17-2ubuntu1
@@ -856,9 +681,8 @@
-zerofree=1.1.1-1
-zfs-dbg=2.1.99-delphix+2022.03.21.19
-zfs-headers-5.4.0-104-dx2022031105-7088c044f-generic=2.1.99-delphix+2022.03.21.19
-zfs-initramfs=2.1.99-delphix+2022.03.21.19
-zfs-modules-5.4.0-104-dx2022031105-7088c044f-generic-dbg=2.1.99-delphix+2022.03.21.19
-zfs-modules-5.4.0-104-dx2022031105-7088c044f-generic=2.1.99-delphix+2022.03.21.19
-zfs-test=2.1.99-delphix+2022.03.21.19
-zfs-zed=2.1.99-delphix+2022.03.21.19
-zfsutils-linux=2.1.99-delphix+2022.03.21.19
+zfs-dbg=2.1.99-delphix+2022.03.22.19
+zfs-headers-5.4.0-104-dx2022031105-7088c044f-generic=2.1.99-delphix+2022.03.22.19
+zfs-initramfs=2.1.99-delphix+2022.03.22.19
+zfs-modules-5.4.0-104-dx2022031105-7088c044f-generic-dbg=2.1.99-delphix+2022.03.22.19
+zfs-modules-5.4.0-104-dx2022031105-7088c044f-generic=2.1.99-delphix+2022.03.22.19
+zfs-test=2.1.99-delphix+2022.03.22.19
+zfs-zed=2.1.99-delphix+2022.03.22.19
+zfsutils-linux=2.1.99-delphix+2022.03.22.19
```

**Review by sdimitro — APPROVED** [review]
ShipIt - Pending testing after the removal of the XXX section

**Review by sebroy — APPROVED** [review]

**Comment by prakashsurya** [comment]
Here's the final diff of the packages before and after: 
```
--- before/external-standard-esx.packages.list	2022-04-01 13:59:07.000000000 +0000
+++ after/external-standard-esx.packages.list	2022-04-01 21:00:32.000000000 +0000
@@ -5,2 +4,0 @@
-alsa-topology-conf=1.2.2-1
-alsa-ucm-conf=1.2.2-1ubuntu0.12
@@ -9 +6,0 @@
-apparmor=2.13.3-7ubuntu5.1
@@ -30 +26,0 @@
-blt=2.5.3+dfsg-4
@@ -33 +28,0 @@
-bridge-utils=1.6-2ubuntu1
@@ -51 +45,0 @@
-crash=7.2.8-1ubuntu1.20.04.1
@@ -57 +50,0 @@
-dbus-user-session=1.12.16-2ubuntu2.1
@@ -59,2 +51,0 @@
-dconf-gsettings-backend=0.36.0-1
-dconf-service=0.36.0-1
@@ -66 +57 @@
-delphix-build-info=1.0.0-delphix-2022.04.01.06.17.38-cc65bd41
+delphix-build-info=1.0.0-delphix-2022.04.01.20.18.51-87eaf1b1
@@ -68 +59 @@
-delphix-masking=1.0.0-20220331T075434
+delphix-masking=1.0.0-20220401T153304
@@ -72 +63 @@
-delphix-virtualization=2022.03.31.14
+delphix-virtualization=2022.04.01.07
@@ -75 +65,0 @@
-dirmngr=2.2.19-3ubuntu2.1
@@ -80,3 +69,0 @@
-dmsetup=2:1.02.167-1ubuntu1
-dns-root-data=2019052802
-dnsmasq-base=2.80-1.1ubuntu1.4
@@ -92 +78,0 @@
-eatmydata=105-7
@@ -97 +82,0 @@
-emacs-el=1:26.3+1-1ubuntu2
@@ -103 +87,0 @@
-finalrd=6~ubuntu20.04.1
@@ -110,5 +93,0 @@
-fonts-droid-fallback=1:6.0.1r16-1.1
-fonts-lyx=2.3.4.2-2
-fonts-noto-mono=20200323-1build1~ubuntu20.04.1
-fonts-urw-base35=20170801.1-3
-fuse=2.9.9-3
@@ -118 +96,0 @@
-gdbserver=9.2-0ubuntu1~20.04.1
@@ -121 +98,0 @@
-ghostscript=9.50~dfsg-5ubuntu4.5
@@ -123,15 +99,0 @@
-gir1.2-packagekitglib-1.0=1.1.13-2ubuntu1.1
-git-man=1:2.25.1-1ubuntu3.2
-git=1:2.25.1-1ubuntu3.2
-glib-networking-common=2.64.2-1ubuntu0.1
-glib-networking-services=2.64.2-1ubuntu0.1
-glib-networking=2.64.2-1ubuntu0.1
-gnupg-l10n=2.2.19-3ubuntu2.1
-gnupg-utils=2.2.19-3ubuntu2.1
-gnupg=2.2.19-3ubuntu2.1
-gpg-agent=2.2.19-3ubuntu2.1
-gpg-wks-client=2.2.19-3ubuntu2.1
-gpg-wks-server=2.2.19-3ubuntu2.1
-gpg=2.2.19-3ubuntu2.1
-gpgconf=2.2.19-3ubuntu2.1
-gpgsm=2.2.19-3ubuntu2.1
@@ -147,2 +108,0 @@
-gsettings-desktop-schemas=3.36.0-1ubuntu1
-gsfonts=1:8.11+urwcyr1.0.7~pre44-4.4
@@ -156 +115,0 @@
-ibverbs-providers=28.0-1ubuntu1
@@ -158,3 +116,0 @@
-imagemagick-6-common=8:6.9.10.23+dfsg-2.1ubuntu11.4
-imagemagick-6.q16=8:6.9.10.23+dfsg-2.1ubuntu11.4
-imagemagick=8:6.9.10.23+dfsg-2.1ubuntu11.4
@@ -175,2 +130,0 @@
-isc-dhcp-common=4.4.1-2.1ubuntu5.20.04.2
-iso-codes=4.4-1
@@ -179 +132,0 @@
-javascript-common=11
@@ -189 +141,0 @@
-krb5-locales=1.17-6ubuntu4.1
@@ -197 +148,0 @@
-libappstream4=0.12.10-2
@@ -204 +154,0 @@
-libassuan0=2.5.3-7ubuntu2
@@ -207 +156,0 @@
-libatm1=1:2.5.1-4
@@ -219 +167,0 @@
-libblas3=3.9.0-1build1
@@ -229 +176,0 @@
-libc6-dbg=2.31-0ubuntu9.7
@@ -238,3 +184,0 @@
-libcc1-0=10.3.0-1ubuntu1~20.04
-libcgi-fast-perl=1:2.15-1
-libcgi-pm-perl=4.46-1
@@ -242 +185,0 @@
-libclass-accessor-perl=0.51-1
@@ -244 +186,0 @@
-libcommon-sense-perl=3.74-2build6
@@ -259 +200,0 @@
-libdconf1=0.36.0-1
@@ -262,2 +202,0 @@
-libdjvulibre-text=3.5.27.1-14ubuntu0.1
-libdjvulibre21=3.5.27.1-14ubuntu0.1
@@ -269 +207,0 @@
-libeatmydata1=105-7
@@ -274,3 +211,0 @@
-libencode-locale-perl=1.05-1
-liberror-perl=0.17029-1
-libestr0=0.1.10-2.1
@@ -278,2 +212,0 @@
-libevent-core-2.1-7=2.1.11-stable-1
-libevent-pthreads-2.1-7=2.1.11-stable-1
@@ -282,2 +214,0 @@
-libfastjson4=0.99.8-2
-libfcgi-perl=0.79-1
@@ -286 +216,0 @@
-libfftw3-double3=3.3.8-2ubuntu1
@@ -288 +217,0 @@
-libfile-fcntllock-perl=0.22-3build4
@@ -295,2 +223,0 @@
-libgail-common=2.24.32-4ubuntu4
-libgail18=2.24.32-4ubuntu4
@@ -304 +230,0 @@
-libgdk-pixbuf2.0-bin=2.40.0+dfsg-3ubuntu0.2
@@ -307 +232,0 @@
-libgfortran5=10.3.0-1ubuntu1~20.04
@@ -312,2 +236,0 @@
-libglib2.0-bin=2.64.6-1~ubuntu20.04.4
-libglib2.0-data=2.64.6-1~ubuntu20.04.4
@@ -321,2 +243,0 @@
-libgs9-common=9.50~dfsg-5ubuntu4.5
-libgs9=9.50~dfsg-5ubuntu4.5
@@ -326 +246,0 @@
-libgstreamer1.0-0=1.16.2-2
@@ -328 +247,0 @@
-libgtk2.0-bin=2.24.32-4ubuntu4
@@ -335,4 +253,0 @@
-libhtml-parser-perl=3.72-5
-libhtml-tagset-perl=3.20-4
-libhttp-date-perl=6.05-1
-libhttp-message-perl=6.22-1
@@ -343 +257,0 @@
-libidn11=1.33-2.2ubuntu2
@@ -345,3 +258,0 @@
-libijs-0.35=0.35-15
-libilmbase24=2.3.0-6build1
-libimagequant0=2.12.2-1.1
@@ -349,2 +259,0 @@
-libio-html-perl=1.001-1
-libio-string-perl=1.08-3
@@ -357 +265,0 @@
-libjbig2dec0=0.18-1ubuntu1
@@ -361,2 +268,0 @@
-libjs-jquery-ui=1.12.1+dfsg-5
-libjs-jquery=3.3.1~dfsg-3
@@ -365 +270,0 @@
-libjson-xs-perl=4.020-1build1
@@ -378,2 +282,0 @@
-libksba8=1.3.5-2
-liblapack3=3.9.0-1build1
@@ -386 +288,0 @@
-liblqr-1-0=0.4.2-2.1
@@ -389 +290,0 @@
-liblwp-mediatypes-perl=6.04-1
@@ -395,3 +295,0 @@
-libmagickcore-6.q16-6-extra=8:6.9.10.23+dfsg-2.1ubuntu11.4
-libmagickcore-6.q16-6=8:6.9.10.23+dfsg-2.1ubuntu11.4
-libmagickwand-6.q16-6=8:6.9.10.23+dfsg-2.1ubuntu11.4
@@ -409,2 +307 @@
-libnetpbm10=2:10.0-15.3build1
-libnetplan0=0.103-0ubuntu5~20.04.6
+libnetplan0=0.104-0ubuntu2~20.04.1
@@ -425,3 +321,0 @@
-libnpth0=1.6-1
-libnss-mymachines=245.4-4ubuntu3.15
-libnss-systemd=245.4-4ubuntu3.15
@@ -433,2 +326,0 @@
-libopenexr24=2.3.0-6ubuntu0.5
-libopenjp2-7=2.3.1-1ubuntu4.20.04.1
@@ -437,2 +328,0 @@
-libpackagekit-glib2-18=1.1.13-2ubuntu1.1
-libpam-cap=1:2.32-1
@@ -447,3 +336,0 @@
-libpaper-utils=1.1.28
-libpaper1=1.1.28
-libparse-debianchangelog-perl=1.2.0-13
@@ -464 +350,0 @@
-libproxy1v5=0.4.15-10ubuntu1.2
@@ -474 +359,0 @@
-libquadmath0=10.3.0-1ubuntu1~20.04
@@ -485 +369,0 @@
-libsasl2-modules=2.1.27+dfsg-2ubuntu0.1
@@ -505,2 +388,0 @@
-libsodium23=1.0.18-1
-libsoup2.4-1=2.70.0-1
@@ -515,2 +396,0 @@
-libstemmer0d=0+svn585-2
-libsub-name-perl=0.26-1
@@ -521 +400,0 @@
-libtcl8.6=8.6.10+dfsg-1
@@ -531 +409,0 @@
-libtimedate-perl=2.3200-1
@@ -535,2 +412,0 @@
-libtk8.6=8.6.10-1
-libtypes-serialiser-perl=1.0-1
@@ -541 +416,0 @@
-liburi-perl=1.76-2
@@ -551,2 +425,0 @@
-libwebpdemux2=0.6.1-2ubuntu0.20.04.1
-libwebpmux3=0.6.1-2ubuntu0.20.04.1
@@ -557 +429,0 @@
-libwmf0.2-7=0.2.8.4-17ubuntu1
@@ -574 +445,0 @@
-libxft2=2.3.3-0ubuntu1
@@ -581 +451,0 @@
-libxmuu1=2:1.1.3-0ubuntu1
@@ -586 +455,0 @@
-libxss1=1:1.2.3-1
@@ -629 +497,0 @@
-ncurses-term=6.2-0ubuntu2
@@ -634,3 +502 @@
-netpbm=2:10.0-15.3build1
-netplan.io=0.103-0ubuntu5~20.04.6
-networkd-dispatcher=2.1-2~ubuntu20.04.1
+netplan.io=0.104-0ubuntu2~20.04.1
@@ -655,3 +520,0 @@
-os-prober=1.74ubuntu2
-packagekit-tools=1.1.13-2ubuntu1.1
-packagekit=1.1.13-2ubuntu1.1
@@ -671 +533,0 @@
-pinentry-curses=1.1.0-3build1
@@ -673 +534,0 @@
-poppler-data=0.4.9-2
@@ -682 +542,0 @@
-psutils=1.17.dfsg-4
@@ -685 +544,0 @@
-publicsuffix=20200303.0012-1
@@ -690 +548,0 @@
-python-matplotlib-data=3.1.2-1ubuntu4
@@ -701 +558,0 @@
-python3-bcrypt=3.1.7-2ubuntu1
@@ -711 +567,0 @@
-python3-cycler=0.10.0-3
@@ -718 +573,0 @@
-python3-distro=1.4.0-1
@@ -732,2 +586,0 @@
-python3-kerberos=1.1.14-3.1build1
-python3-kiwisolver=1.0.1-3build1
@@ -736 +588,0 @@
-python3-matplotlib=3.1.2-1ubuntu4
@@ -739 +590,0 @@
-python3-nacl=1.3.0-5
@@ -741,2 +591,0 @@
-python3-ntlm-auth=1.1.0-1
-python3-numpy=1:1.17.4-5ubuntu3
@@ -744 +592,0 @@
-python3-olefile=0.46-2
@@ -746,2 +593,0 @@
-python3-paramiko=2.6.0-2ubuntu0.1
-python3-pil=7.0.0-4ubuntu0.5
@@ -752 +597,0 @@
-python3-pygments=2.3.1+dfsg-1ubuntu2.2
@@ -756,3 +600,0 @@
-python3-requests-kerberos=0.12.0-2
-python3-requests-ntlm=1.1.0-1
-python3-requests-unixsocket=0.2.0-2
@@ -768,2 +609,0 @@
-python3-software-properties=0.99.9.8
-python3-tk=3.8.10-0ubuntu1~20.04
@@ -774,2 +613,0 @@
-python3-winrm=0.3.0-2
-python3-xmltodict=0.12.0-1
@@ -785,2 +623 @@
-rsync=3.1.3-8ubuntu0.2
-rsyslog=8.2001.0-1ubuntu1.1
+rsync=3.1.3-8ubuntu0.3
@@ -801,2 +637,0 @@
-sntp=1:4.2.8p12+dfsg-3ubuntu4.20.04.1
-software-properties-common=0.99.9.8
@@ -804 +638,0 @@
-ssh-import-id=5.10-0ubuntu1
@@ -818 +651,0 @@
-tk8.6-blt2.5=2.5.3+dfsg-4
@@ -823 +655,0 @@
-ttf-bitstream-vera=1.10-8
@@ -827 +658,0 @@
-ubuntu-fan=0.12.13
@@ -834 +664,0 @@
-unattended-upgrades=2.3ubuntu0.1
@@ -850,2 +679,0 @@
-xauth=1:1.1-0ubuntu1
-xdg-user-dirs=0.17-2ubuntu1
@@ -856 +683,0 @@
-zerofree=1.1.1-1
@@ -866 +693 @@
-zlib1g=1:1.2.11.dfsg-2ubuntu1.2
+zlib1g=1:1.2.11.dfsg-2ubuntu1.3
```

**Pull request merged**
