### PR TITLE
Remove logic that configures swap on ZVOL

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/82/)

**Comment by shartse** [comment]
Since we're now noticing the recv EBUSY failures on master even with zvol swap, we may want to go ahead with this sooner to get rid of the hangs.

**Comment by prakashsurya** [comment]
@shartse what (if any) verification do we want to do, before landing this? cc @sebroy @grwilson 

I've booted the image `git-ab-pre-push` generated, and it doesn't have swap configured as expected.

**Comment by shartse** [comment]
@prakashsurya we should probably do some `dx-test` runs to see if we run into any memory-related issues that we haven't noticed yet.  Want to kick off a few runs? You can send me some of them to monitor.

**Comment by prakashsurya** [comment]
I kicked of an integration run [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/dx-integration-tests/9297/console)

**Comment by prakashsurya** [comment]
Rebased onto master, kicked off `git-ab-pre-push` [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/projects/job/dx4linux/job/appliance-build-orchestrator-pre-push/90/). I'll start an integration run when that finishes.

**Comment by prakashsurya** [comment]
Unfortunately, the integration test job kicked of by `git-ab-pre-push` fails with some unrelated error:
```
15:50:11 + python git-utils/bin/get-dlpx-release-by-branch -b
15:50:12 usage: get-dlpx-release-by-branch [-h] -b BRANCH
15:50:12 get-dlpx-release-by-branch: error: argument -b/--branch: expected one argument
```
See [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/dx-integration-tests/9313/console)

**Comment by prakashsurya** [comment]
I think I've managed to start a `git dx-test` run of `master`, but using my DCOA image that is configured not to use swap; see [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/dx-integration-tests/9315/console).

Logging into at VM created by that run shows me this:
```
$ ssh delphix@split-precommit-dxos-11054-66511f0c.dlpxdc.co
...
$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0   70G  0 disk 
├─xvda1 202:1    0   70G  0 part 
└─xvda2 202:2    0 1007K  0 part 
xvdb    202:16   0    8G  0 disk 
xvdc    202:32   0    8G  0 disk 
xvdd    202:48   0    8G  0 disk 
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7463        3093        3881          40         488        4096
Swap:             0           0           0
```
So I think I kicked off this run correctly.

**Pull request merged**
