### PR TITLE
Add "bpfcc-tools" package to base configuration

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by ahrens** [comment]
Is this part of `bcc`?  Can we get rid of the source dir then?  Or is this a requirement for `bcc`?

**Comment by prakashsurya** [comment]
So far, I've only looked at what the list of files says, [here](https://packages.ubuntu.com/bionic/all/bpfcc-tools/filelist).

**Comment by ahrens** [comment]
huh, I don't see `bcc` in there.  Do those tools work without bcc installed?

**Comment by prakashsurya** [comment]
Looks like this package depends on python-bpfcc, which then depends on libbpfcc.

**Comment by prakashsurya** [comment]
I installed this package onto an existing `dlpx-linux-trunk` VM, and used a couple of the tools to verify they worked:
```
$ sudo trace-bpfcc -K zil_commit                                                
PID    TID    COMM         FUNC                                                    
6648   6648   kworker/u30:1 zil_commit                                             
        zil_commit+0x1 [kernel]                                                    
        do_writepages+0x4b [kernel]                                                
        __writeback_single_inode+0x45 [kernel]                                     
        writeback_sb_inodes+0x1e1 [kernel]                                         
        wb_writeback+0x107 [kernel]                                                
        wb_workfn+0xb3 [kernel]                                                    
        process_one_work+0x1de [kernel]                                            
        worker_thread+0x32 [kernel]                                                
        kthread+0x121 [kernel]                                                     
        ret_from_fork+0x35 [kernel] 
```
```
$ sudo filetop-bpfcc -C                                                            
Tracing... Output every 1 secs. Hit Ctrl-C to end                                  
                                                                                   
13:35:50 loadavg: 0.22 0.07 0.02 2/229 14246                                       
                                                                                   
TID    COMM             READS  WRITES R_Kb    W_Kb    T FILE                       
3113   atopacctd        14     0      218     0       R pacct_source               
14218  bash             4      0      3       0       R continuum_save.sh          
14216  filetop-bpfcc    2      0      2       0       R loadavg                    
31023  tmux: server     2      0      2       0       R cmdline                    
14222  bash             4      0      1       0       R check_tmux_version.sh   
14218  bash             1      0      1       0       R variables.sh               
14245  date             2      0      1       0       R UTC                        
14242  tmux             2      0      1       0       R UTC                        
14236  tmux             2      0      1       0       R UTC                        
14239  tmux             2      0      1       0       R UTC                        
14229  tmux             2      0      1       0       R UTC                        
14218  bash             1      0      0       0       R helpers.sh                 
14236  tmux             1      0      0       0       R libc-2.27.so               
14239  tmux             1      0      0       0       R libutempter.so.1.1.6       
14239  tmux             1      0      0       0       R libtinfo.so.5.9            
14229  tmux             1      0      0       0       R libevent-2.1.so.6.0.2   
14229  tmux             1      0      0       0       R libutempter.so.1.1.6       
14239  tmux             1      0      0       0       R libpthread-2.27.so         
14239  tmux             1      0      0       0       R libutil-2.27.so            
14226  tr               1      0      0       0       R libc-2.27.so
```

And the list of `bpfcc` packages installed:
```
$ dpkg -l | grep bpfcc
ii  bpfcc-tools                           0.5.0-5ubuntu1                             all          tools for BPF Compiler Collection (BCC)
ii  libbpfcc                              0.5.0-5ubuntu1                             amd64        shared library for BPF Compiler Collection (BCC)
ii  python-bpfcc                          0.5.0-5ubuntu1                             all          Python wrappers for BPF Compiler Collection (BCC)
```

Files installed by the `python-bpfcc` package:
```
$ dpkg -L python-bpfcc
/.
/usr
/usr/lib
/usr/lib/python2.7
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/bcc
/usr/lib/python2.7/dist-packages/bcc/__init__.py
/usr/lib/python2.7/dist-packages/bcc/libbcc.py
/usr/lib/python2.7/dist-packages/bcc/perf.py
/usr/lib/python2.7/dist-packages/bcc/table.py
/usr/lib/python2.7/dist-packages/bcc/usdt.py
/usr/lib/python2.7/dist-packages/bcc/utils.py
/usr/lib/python2.7/dist-packages/bcc-0.5.0.egg-info
/usr/share
/usr/share/doc
/usr/share/doc/python-bpfcc
/usr/share/doc/python-bpfcc/copyright
/usr/share/doc/python-bpfcc/NEWS.Debian.gz
/usr/share/doc/python-bpfcc/README.Debian
/usr/share/doc/python-bpfcc/changelog.Debian.gz
```

Files installed by the `libbpfcc` package:
```
$ dpkg -L libbpfcc
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libbcc.so.0.5.0
/usr/share
/usr/share/doc
/usr/share/doc/libbpfcc
/usr/share/doc/libbpfcc/FAQ.txt
/usr/share/doc/libbpfcc/NEWS.Debian.gz
/usr/share/doc/libbpfcc/README.Debian
/usr/share/doc/libbpfcc/README.md.gz
/usr/share/doc/libbpfcc/changelog.Debian.gz
/usr/share/doc/libbpfcc/copyright
/usr/lib/x86_64-linux-gnu/libbcc.so
/usr/lib/x86_64-linux-gnu/libbcc.so.0
```

**Pull request merged**
