### PR TITLE
DLPX-65914 in-place upgrade does not update grub to the latest kernel

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2070/)

**Comment by grwilson** [comment]
I also tested this change on my VM where I originally saw the problem and confirmed that it applied the grub change and after rebooting booted the correct version.

**Pull request merged**
