### PR TITLE
DLPX-64201 determine how to remove old linux kernels

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
I tested this by taking a 6.0.0.0 engine, and doing a upgrade to it for each version up to 6.0.8.0, and then ran upgrade and verfied the installed kernels before and after the final upgrade:
```
$ uname -r
5.3.0-53-generic

$ dpkg -l | grep delphix-kernel
ii  delphix-kernel-5.0.0-29-generic                             1.0.0-delphix-2020.02.25.19                     amd64        Kernel packages consolidation for the Delphix Appliance.
ii  delphix-kernel-5.0.0-37-generic                             1.0.0-delphix-2020.05.03.01                     amd64        Kernel packages consolidation for the Delphix Appliance.
ii  delphix-kernel-5.3.0-53-generic                             1.0.0-delphix-2020.09.03.14                     amd64        Kernel packages consolidation for the Delphix Appliance.
ii  delphix-kernel-5.4.0-42-generic                             1.0.0-delphix-2021.02.16.17                     amd64        Kernel packages consolidation for the Delphix Appliance.
ii  delphix-kernel-5.4.0-65-dx2021050505-63c44010f-generic      1.0.0-delphix-2021.05.05.06                     amd64        Kernel packages consolidation for the Delphix Appliance.


$ sudo /var/dlpx-update/latest/execute -p esx
$ dpkg -l | grep delphix-kernel
ii  delphix-kernel-5.3.0-53-generic                             1.0.0-delphix-2020.09.03.14                                                                                amd64        Kernel packages consolidation for the Delphix Appliance.
ii  delphix-kernel-5.4.0-65-dx2021031005-3e6ea35a1-generic      1.0.0-delphix-2021.03.10.06                                                                                amd64        Kernel packages consolidation for the Delphix Appliance.
```

**Comment by prakashsurya** [comment]
I think this will need a bit more work.. looking more closely, we're still not removing all the kernel related packages:
```
$ dpkg -l | grep linux-image
ii  linux-image-5.3.0-53-generic                                5.3.0-53.47~18.04.1                                                                                        amd64        Signed kernel image generic
ii  linux-image-5.4.0-42-generic                                5.4.0-42.46~18.04.1                                                                                        amd64        Signed kernel image generic
ii  linux-image-5.4.0-65-dx2021031005-3e6ea35a1-generic         5.4.0-65.73~18.04.1                                                                                        amd64        Linux kernel image for version 5.4.0 on 64 bit x86 SMP
ii  linux-image-5.4.0-65-dx2021031005-3e6ea35a1-generic-dbgsym  5.4.0-65.73~18.04.1                                                                                        amd64        Linux kernel debug image for version 5.4.0 on 64 bit x86 SMP
ii  linux-image-5.4.0-65-dx2021050505-63c44010f-generic         5.4.0-65.73~18.04.1                                                                                        amd64        Linux kernel image for version 5.4.0 on 64 bit x86 SMP
ii  linux-image-generic-hwe-18.04                               5.4.0.42.46~18.04.35                                                                                       amd64        Generic Linux kernel image
```
i.e. `linux-image-5.4.0-42-generic` and `linux-image-5.4.0-65-dx2021050505-63c44010f-generic` should not be installed anymore, but they still are.

```
$ aptitude why linux-image-5.4.0-65-dx2021050505-63c44010f-generic
i   zfs-initramfs                                       Depends  zfs-modules | zfs-dkms                             
i A zfs-modules-5.4.0-65-dx2021050505-63c44010f-generic Provides zfs-modules                                        
i A zfs-modules-5.4.0-65-dx2021050505-63c44010f-generic Depends  linux-image-5.4.0-65-dx2021050505-63c44010f-generic

$ aptitude why linux-image-5.4.0-42-generic
i   delphix-kernel-5.3.0-53-generic Depends linux-generic-hwe-18.04                               
i A linux-generic-hwe-18.04         Depends linux-image-generic-hwe-18.04 (= 5.4.0.42.46~18.04.35)
i A linux-image-generic-hwe-18.04   Depends linux-image-5.4.0-42-generic

**Comment by prakashsurya** [comment]
It's a similar situation for the zfs-modules package:
```
$ dpkg -l | grep zfs-modules
ii  zfs-modules-5.3.0-53-generic                                0.8.0-delphix+2020.09.03.14                                                                                amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.3.0-53-generic)
ii  zfs-modules-5.3.0-53-generic-dbg                            0.8.0-delphix+2020.09.03.14                                                                                amd64        Debugging symbols for OpenZFS userland libraries and tools
ii  zfs-modules-5.4.0-42-generic                                0.8.0-delphix+2021.02.16.17                                                                                amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.4.0-42-generic)
ii  zfs-modules-5.4.0-65-dx2021031005-3e6ea35a1-generic         2.0.0-delphix+2021.05.12.15                                                                                amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.4.0-65-dx2021031005-3e6ea35a1-generic)
ii  zfs-modules-5.4.0-65-dx2021031005-3e6ea35a1-generic-dbg     2.0.0-delphix+2021.05.12.15                                                                                amd64        Debugging symbols for OpenZFS userland libraries and tools
ii  zfs-modules-5.4.0-65-dx2021050505-63c44010f-generic         0.8.0-delphix+2021.05.05.06                                                                                amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.4.0-65-dx2021050505-63c44010f-generic)

$ aptitude why zfs-modules-5.4.0-42-generic
i   zfs-initramfs                Depends  zfs-modules | zfs-dkms
i A zfs-modules-5.4.0-42-generic Provides zfs-modules           

$ aptitude why zfs-modules-5.4.0-65-dx2021050505-63c44010f-generic
i   zfs-initramfs                                       Depends  zfs-modules | zfs-dkms
i A zfs-modules-5.4.0-65-dx2021050505-63c44010f-generic Provides zfs-modules
```

**Comment by prakashsurya** [comment]
I think this latest iteration might be the behavior we want... @pzakha let me know what you think, when you get a chance to look this over.

### Before
```
$ uname -r
5.3.0-53-generic

$ dpkg -l | grep delphix-kernel
ii  delphix-kernel-5.0.0-29-generic                             1.0.0-delphix-2020.02.25.19                     amd64        Kernel packages consolidation for the Delphix Appliance.
ii  delphix-kernel-5.0.0-37-generic                             1.0.0-delphix-2020.05.03.01                     amd64        Kernel packages consolidation for the Delphix Appliance.
ii  delphix-kernel-5.3.0-53-generic                             1.0.0-delphix-2020.09.03.14                     amd64        Kernel packages consolidation for the Delphix Appliance.
ii  delphix-kernel-5.4.0-42-generic                             1.0.0-delphix-2021.02.16.17                     amd64        Kernel packages consolidation for the Delphix Appliance.
ii  delphix-kernel-5.4.0-65-dx2021050505-63c44010f-generic      1.0.0-delphix-2021.05.05.06                     amd64        Kernel packages consolidation for the Delphix Appliance.

$ dpkg -l | grep linux-image
ii  linux-image-5.0.0-29-generic                                5.0.0-29.31~18.04.1                             amd64        Signed kernel image generic
ii  linux-image-5.0.0-37-generic                                5.0.0-37.40~18.04.1                             amd64        Signed kernel image generic
ii  linux-image-5.3.0-53-generic                                5.3.0-53.47~18.04.1                             amd64        Signed kernel image generic
ii  linux-image-5.4.0-42-generic                                5.4.0-42.46~18.04.1                             amd64        Signed kernel image generic
ii  linux-image-5.4.0-42-generic-dbgsym                         5.4.0-42.46~18.04.1                             amd64        Signed kernel image generic
ii  linux-image-5.4.0-65-dx2021050505-63c44010f-generic         5.4.0-65.73~18.04.1                             amd64        Linux kernel image for version 5.4.0 on 64 bit x86 SMP
ii  linux-image-5.4.0-65-dx2021050505-63c44010f-generic-dbgsym  5.4.0-65.73~18.04.1                             amd64        Linux kernel debug image for version 5.4.0 on 64 bit x86 SMP
ii  linux-image-generic-hwe-18.04                               5.4.0.42.46~18.04.35                            amd64        Generic Linux kernel image
ii  linux-image-unsigned-5.4.0-42-generic-dbgsym                5.4.0-42.46~18.04.1                             amd64        Linux kernel debug image for version 5.4.0 on 64 bit x86 SMP

$ dpkg -l | grep zfs-modules
ii  zfs-modules-5.0.0-29-generic                                0.8.0-delphix+2020.02.25.19                     amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.0.0-29-generic)
ii  zfs-modules-5.0.0-37-generic                                0.8.0-delphix+2020.05.03.01                     amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.0.0-37-generic)
ii  zfs-modules-5.3.0-53-generic                                0.8.0-delphix+2020.09.03.14                     amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.3.0-53-generic)
ii  zfs-modules-5.3.0-53-generic-dbg                            0.8.0-delphix+2020.09.03.14                     amd64        Debugging symbols for OpenZFS userland libraries and tools
ii  zfs-modules-5.4.0-42-generic                                0.8.0-delphix+2021.02.16.17                     amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.4.0-42-generic)
ii  zfs-modules-5.4.0-42-generic-dbg                            0.8.0-delphix+2021.02.16.17                     amd64        Debugging symbols for OpenZFS userland libraries and tools
ii  zfs-modules-5.4.0-65-dx2021050505-63c44010f-generic         0.8.0-delphix+2021.05.05.06                     amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.4.0-65-dx2021050505-63c44010f-generic)
ii  zfs-modules-5.4.0-65-dx2021050505-63c44010f-generic-dbg     0.8.0-delphix+2021.05.05.06                     amd64        Debugging symbols for OpenZFS userland libraries and tools
```

### After
```
$ sudo /var/dlpx-update/latest/execute -p esx
$ uname -r
5.3.0-53-generic

$ dpkg -l | grep delphix-kernel
ii  delphix-kernel-5.4.0-65-dx2021031005-3e6ea35a1-generic      1.0.0-delphix-2021.03.10.06                                                                                amd64        Kernel packages consolidation for the Delphix Appliance.

$ dpkg -l | grep linux-image
ii  linux-image-5.3.0-53-generic                                5.3.0-53.47~18.04.1                                                                                        amd64        Signed kernel image generic
ii  linux-image-5.4.0-65-dx2021031005-3e6ea35a1-generic         5.4.0-65.73~18.04.1                                                                                        amd64        Linux kernel image for version 5.4.0 on 64 bit x86 SMP
ii  linux-image-5.4.0-65-dx2021031005-3e6ea35a1-generic-dbgsym  5.4.0-65.73~18.04.1                                                                                        amd64        Linux kernel debug image for version 5.4.0 on 64 bit x86 SMP

$ dpkg -l | grep zfs-modules
ii  zfs-modules-5.3.0-53-generic                                0.8.0-delphix+2020.09.03.14                                                                                amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.3.0-53-generic)
ii  zfs-modules-5.3.0-53-generic-dbg                            0.8.0-delphix+2020.09.03.14                                                                                amd64        Debugging symbols for OpenZFS userland libraries and tools
ii  zfs-modules-5.4.0-65-dx2021031005-3e6ea35a1-generic         2.0.0-delphix+2021.05.12.15                                                                                amd64        OpenZFS filesystem kernel modules for Linux (kernel 5.4.0-65-dx2021031005-3e6ea35a1-generic)
ii  zfs-modules-5.4.0-65-dx2021031005-3e6ea35a1-generic-dbg     2.0.0-delphix+2021.05.12.15                                                                                amd64        Debugging symbols for OpenZFS userland libraries and tools
```

**Review by pzakha — APPROVED** [review]

**Review by sebroy — APPROVED** [review]
Learned something new today: `apt-mark`. Thanks!

**Pull request merged**
