### PR TITLE
Add new commit status to bors configuration

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
cc: @pzakha

bors try

**Comment by prakashsurya** [comment]
bors try

**Comment by pzakha** [comment]
This should only be integrated after our automation posts statuses properly.
It would be worth it to add some context in the description.

**Comment by prakashsurya** [comment]
We’re posting the statuses. You can see them in the UI. The “bors try” would have failed otherwise.

**Pull request merged**
