### PR TITLE
Revert "DLPX-61762 Linux verify fails, Unable to acquire the dpkg frontend lock"

### PR DESCRIPTION
**Pull request by prakashsurya**
This reverts commit 9da3c1e6835d975e1a2bf46147420d7b0720fcb3.

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1327/)

**Comment by prakashsurya** [comment]
cc: @pandar00 .. I also opened [DLPX-64475](https://jira.delphix.com/browse/DLPX-64475) .. Let me know if you'd like to try to fix this instead of doing the revert, but I think "not-in-place" is broken at the moment.

**Comment by pandar00** [comment]
@prakashsurya It'd be best to revert for now. Thanks for doing this.
I'll work on the bug once I finish with the escalation.

**Pull request merged**
