### PR TITLE
WIP: Use "delphix.target" to restart services on upgrade

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1858/)

**Comment by pzakha** [comment]
Would this also attempt to restart `delphix-mgmt` inside a container?
Also, is this still a Work In Prgoress?

**Comment by prakashsurya** [comment]
> Would this also attempt to restart delphix-mgmt inside a container?

No; "delphix-mgmt.service" doesn't run in the upgrade container.

> Also, is this still a Work In Prgoress?

Yes; I still need to test and do manual verification.

**Comment by pzakha** [comment]
> No; "delphix-mgmt.service" doesn't run in the upgrade container.

Right, just wanted to make sure that this didn't affect that behaviour.
Might be useful to compare the output of running services before this change and after this change.

This LGTM, but I'll take another look once this is not WIP anymore.

**Comment by prakashsurya** [comment]
> Might be useful to compare the output of running services before this change and after this change.

Can you be more specific about what you're requesting? I'm not sure exactly what information you want me to gather...

**Comment by pzakha** [comment]
> Can you be more specific about what you're requesting? I'm not sure exactly what information you want me to gather...

Sorry, was a bit vague. We should just check that this restarts (or starts) all the Delphix services that we expect.

**Pull request closed without merging**
