### PR TITLE
Stop creating VHD

### PR DESCRIPTION
**Pull request by jgallag88**
When we create VM artifacts, we create both a VHD and a VHDX, but only
upload the VHDX. The VHD is completely unused and the script that
creates it can be removed.

### CODE REVIEW

**Comment by jgallag88** [comment]
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/458/console

**Comment by jgallag88** [comment]
cc @grodr

**Comment by prakashsurya** [comment]
bors delegate+

**Pull request merged**
