### PR TITLE
LX-1556 /opt/delphix/server/etc/version differs from <upgrade_package>/version.info

### PR DESCRIPTION
**Pull request by dtzeng**

### CODE REVIEW

**Comment by dtzeng** [comment]
@prakashsurya @pandar00 `grep -q` exits immediately when a match is found, so the `dpkg -l` command is sent a SIGPIPE and exits with status code 141.
https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q

Testing:
`git ab-pre-push -v internal-dev internal-minimal` http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build/job/master/job/pre-push/126/console

Uploaded image, and checked all debian package versions, and version.info is the same
```
delphix@dt-version:/var/dlpx-update/2018.10.30.0$ find public/ -name "delphix-virtualization*deb"
public/pool/delphix/d/delphix-virtualization/delphix-virtualization_2018.10.30.0_amd64.deb
delphix@dt-version:/var/dlpx-update/2018.10.30.0$ find public/ -name "delphix-entire*deb"
public/pool/delphix/d/delphix-entire/delphix-entire_2018.10.30.0_all.deb
delphix@dt-version:/var/dlpx-update/2018.10.30.0$ cat version.info | grep VERSION
VERSION=2018.10.30.0
MINIMUM_VERSION=5.3.0.0
# MINIMUM_VERSION above.
MINIMUM_REBOOT_OPTIONAL_VERSION=5.3.0.0
```

**Comment by dtzeng** [comment]
Yup, I tested with both dev variant and minimal variant.  The image for dev variant is in the above comment.  The image with minimal variant is here:
```
delphix@dt-version:/var/dlpx-update/2018.10.30.11$ find public/ -name "delphix-virtualization*deb"
delphix@dt-version:/var/dlpx-update/2018.10.30.11$ find public/ -name "delphix-entire*deb"
public/pool/delphix/d/delphix-entire/delphix-entire_2018.10.30.11_all.deb
delphix@dt-version:/var/dlpx-update/2018.10.30.11$ cat version.info | grep VERSION
VERSION=2018.10.30.11
MINIMUM_VERSION=5.3.0.0
# MINIMUM_VERSION above.
MINIMUM_REBOOT_OPTIONAL_VERSION=5.3.0.0
```

**Comment by prakashsurya** [comment]
Sorry I meant to do this in my prior comment...

bors delegate+

**Pull request merged**
