### PR TITLE
Use a dedicated dataset for GRUB configuration

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/394/)

**Comment by prakashsurya** [comment]
With this change in place:
```
$ find /boot -maxdepth 3 -mindepth 1
/boot/filesystem.packages
/boot/initrd.img-4.15.0-43-generic
/boot/vmlinuz-4.15.0-43-generic
/boot/System.map-4.15.0-43-generic
/boot/filesystem.packages-remove
/boot/grub
/boot/grub/grubenv
/boot/grub/gfxblacklist.txt
/boot/grub/unicode.pf2
/boot/config-4.15.0-43-generic

$ sudo mount -t zfs rpool/grub /mnt
$ find /mnt -maxdepth 3 -mindepth 1
/mnt/boot
/mnt/boot/grub
/mnt/boot/grub/i386-pc
/mnt/boot/grub/grubenv
/mnt/boot/grub/fonts
/mnt/boot/grub/grub.cfg
/mnt/boot/grub/locale
$ sudo umount /mnt

$ zfs list
NAME                              USED  AVAIL     REFER  MOUNTPOINT
rpool                            13.7G  53.6G       64K  none
rpool/ROOT                       13.7G  53.6G       64K  none
rpool/ROOT/delphix.ZhcLMeg       13.7G  53.6G       64K  none
rpool/ROOT/delphix.ZhcLMeg/data  28.2M  53.6G     28.2M  legacy
rpool/ROOT/delphix.ZhcLMeg/home  6.51G  53.6G     6.51G  legacy
rpool/ROOT/delphix.ZhcLMeg/root  7.15G  53.6G     7.15G  /
rpool/crashdump                  65.5K  17.4G     65.5K  /var/crash
rpool/grub                       3.03M  53.6G     3.03M  legacy
rpool/update                       68K  15.0G       68K  /var/dlpx-update
```

**Comment by prakashsurya** [comment]
Verified "not-in-place" upgrades still work:
```
$ sudo zfs list
NAME                              USED  AVAIL     REFER  MOUNTPOINT
rpool                            28.1G  39.2G       64K  none
rpool/ROOT                       24.6G  39.2G       64K  none
rpool/ROOT/delphix.ZhcLMeg       17.4G  39.2G       64K  none
rpool/ROOT/delphix.ZhcLMeg/data  36.3M  39.2G     33.7M  legacy
rpool/ROOT/delphix.ZhcLMeg/home  10.0G  39.2G     10.0G  legacy
rpool/ROOT/delphix.ZhcLMeg/root  7.34G  39.2G     7.33G  /
rpool/ROOT/delphix.pknLda1       7.17G  39.2G       64K  none
rpool/ROOT/delphix.pknLda1/data  4.73M  39.2G     35.0M  legacy
rpool/ROOT/delphix.pknLda1/home   150K  39.2G     10.0G  legacy
rpool/ROOT/delphix.pknLda1/root  7.17G  39.2G     7.17G  /
rpool/crashdump                  65.5K  17.4G     65.5K  /var/crash
rpool/grub                       3.03M  39.2G     3.03M  legacy
rpool/update                     3.53G  11.5G     3.53G  /var/dlpx-update

$ find /boot -maxdepth 3 -mindepth 1
/boot/initrd.img-4.15.0-43-generic
/boot/vmlinuz-4.15.0-43-generic
/boot/System.map-4.15.0-43-generic
/boot/config-4.15.0-43-generic
/boot/grub
/boot/grub/unicode.pf2
/boot/grub/grubenv
/boot/grub/gfxblacklist.txt

$ sudo mount -t zfs rpool/grub /mnt
$ find /mnt -maxdepth 3 -mindepth 1
/mnt/boot
/mnt/boot/grub
/mnt/boot/grub/i386-pc
/mnt/boot/grub/grubenv
/mnt/boot/grub/fonts
/mnt/boot/grub/grub.cfg
/mnt/boot/grub/locale

$ cat /mnt/boot/grub/grub.cfg
...
menuentry 'Ubuntu' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-a571607826dda33a' {
...
        linux   /ROOT/delphix.pknLda1/root@/boot/vmlinuz-4.15.0-43-generic root=ZFS=rpool/ROOT/delphix.pknLda1/root ro  console=tty0 console=ttyS0,38400n8 ipv6.disable=1 crashkernel=1024M-:512M
        initrd  /ROOT/delphix.pknLda1/root@/boot/initrd.img-4.15.0-43-generic
}
...
```

We still only keep a single entry in the grub configuration. I'll use a seperate PR to change how we manage the grub config, so we can have multiple entries for all of the available root filesystems, like was discussed in the upgrade meeting.

**Comment by prakashsurya** [comment]
cc: @pzakha @grwilson

This appears to be working; it allows us to have a seperate dataset for GRUB, which is the ideal solution based on what we talked about. Since this is only used for GRUB files and configuration, we don't have to worry about any of the negative interactions we discussed, with "dpkg" and how the kernel packages places files in `/boot`; `/boot` is still part of the root filesystem.

**Comment by pzakha** [comment]
Ah, that's interesting, so I'm guessing `grub-common` or some other packages are installing the files:
```
/boot/grub/unicode.pf2
/boot/grub/grubenv
/boot/grub/gfxblacklist.txt
```
I know that `grubenv` is typically used by some frameworks (e.g. `snaps`) to store info that can be loaded and modified at boot time. It would be interesting to see if that's still the case with this construct, as this is something we could perhaps leverage for the recovery environment.

**Pull request merged**
