### PR TITLE
Add information about our code of conduct and contributor agreement.

### PR DESCRIPTION
**Pull request by sebroy**

### CODE REVIEW

**Comment by prakashsurya** [comment]
```
11:31:32 + dc guest wait -t 600 post-push-22-a721e6e9
11:45:13 ERROR:root:Timed out waiting for instances:
11:45:13   post-push-22-a721e6e9
```
Looks like an infrastructure issues.. retrying..

bors r+

**Comment by sebroy** [comment]
One more time... If it fails again, I'm merging this myself! ;-)

bors r+

**Pull request merged**
