### PR TITLE
DLPX-67937 need OCI image

### PR DESCRIPTION
**Pull request by grwilson**

### CODE REVIEW

**Comment by grwilson** [comment]
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2669/flowGraphTable/

delphix-platform changes: https://github.com/delphix/delphix-platform/pull/181

**Comment by pzakha** [comment]
What other testing have you done with this new image?

**Comment by grwilson** [comment]
We are testing the OCI image today and don't plan to merge until we confirm that it works. We have used the generic KVM image so far but it required manual configuration for network (it didn't include NoCloud) and did not have the oracle customized kernel.

**Comment by grwilson** [comment]
Confirmed that OCI works.

**Pull request merged**
