### PR TITLE
Add new "internal-unittest" variant

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
- `git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1453/)
- `git-ab-pre-push -v internal-unittest` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1454/)

**Comment by prakashsurya** [comment]
cc: @basil

**Comment by basil** [comment]
bors delegate+

**Pull request merged**
