### PR TITLE
DLPX-76769 [Backport of DLPX-76694 to 6.0.10.0] Failure to build DelphixConnector on Delphix Engine, causing gui_sanity testing to fail

### PR DESCRIPTION
**Pull request by pzakha**
Clean cherry-pick of #578 

## Testing
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5808/

### CODE REVIEW

**Review by prakashsurya — COMMENTED** [review]
I believe we have all the app-gate build dependencies in the QA variant ansible role, should this be included in that list, rather than here?

**Comment by pzakha** [comment]
> I believe we have all the app-gate build dependencies in the QA variant ansible role, should this be included in that list, rather than here?

I wasn't aware of that, but yeah reading the comment in appliance-build.qa-internal that would probably make sense. I could push a follow-up to the parent bug on master and that backport that instead.

**Review by prakashsurya — APPROVED** [review]
ah, right.. this is a backport, so I think we should keep it consistent with the original master push.

**Comment by pzakha** [comment]
I'll push this backport, then open another review to move this to internal-qa

**Review by rasantel — APPROVED** [review]

**Pull request merged**
